name: Deploy to Dev EC2

on:
    push:
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Deploy to Dev EC2
              env:
                  PRIVATE_KEY: ${{ secrets.DEV_KEY }}
                  HOST: ${{ secrets.DEV_HOST }}
                  USER: ubuntu
              run: |
                  echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
                    cd /home/ubuntu/meera-api &&
                    ./deploy.sh
                  '

            - name: Clean up private key
              run: rm private_key
